/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateIdRouteImport } from './routes/create.$id'
import { Route as CreateIdIIdxRouteImport } from './routes/create.$id.i.$idx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIdRoute = CreateIdRouteImport.update({
  id: '/create/$id',
  path: '/create/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIdIIdxRoute = CreateIdIIdxRouteImport.update({
  id: '/i/$idx',
  path: '/i/$idx',
  getParentRoute: () => CreateIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create/$id': typeof CreateIdRouteWithChildren
  '/create/$id/i/$idx': typeof CreateIdIIdxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create/$id': typeof CreateIdRouteWithChildren
  '/create/$id/i/$idx': typeof CreateIdIIdxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create/$id': typeof CreateIdRouteWithChildren
  '/create/$id/i/$idx': typeof CreateIdIIdxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create/$id' | '/create/$id/i/$idx'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create/$id' | '/create/$id/i/$idx'
  id: '__root__' | '/' | '/create/$id' | '/create/$id/i/$idx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateIdRoute: typeof CreateIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/$id': {
      id: '/create/$id'
      path: '/create/$id'
      fullPath: '/create/$id'
      preLoaderRoute: typeof CreateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/$id/i/$idx': {
      id: '/create/$id/i/$idx'
      path: '/i/$idx'
      fullPath: '/create/$id/i/$idx'
      preLoaderRoute: typeof CreateIdIIdxRouteImport
      parentRoute: typeof CreateIdRoute
    }
  }
}

interface CreateIdRouteChildren {
  CreateIdIIdxRoute: typeof CreateIdIIdxRoute
}

const CreateIdRouteChildren: CreateIdRouteChildren = {
  CreateIdIIdxRoute: CreateIdIIdxRoute,
}

const CreateIdRouteWithChildren = CreateIdRoute._addFileChildren(
  CreateIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateIdRoute: CreateIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
